# -*- coding: utf-8 -*-
"""sistema_livros.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17a2oPhlkeJRtjeaFcRjXHNoHaigZfFL7
"""

ARQUIVO = "livros.txt"

# --- Cadastro ---
def cadastrar_livro(titulo, autor):
  with open(ARQUIVO, "a", encoding="utf-8") as f:
    f.write(f"{titulo};{autor}\n")
  print(f"Livro '{titulo}' cadastrado com sucesso!")

# --- Busca ---
def buscar_livro(titulo):
    try:
        with open(ARQUIVO, "r", encoding="utf-8") as f:
            for linha in f:
                nome, autor = linha.strip().split(";")
                # Linha: Dom Casmurro; Machado de Assis -> Lista: ['Dom Camurro', 'Machado de Assis']
                if nome.lower() == titulo.lower():
                    print(f"Livro encontrado: {nome} (Autor: {autor})")
                    return
        print("Livro não encontrado.")
    except FileNotFoundError:
        print("Arquivo ainda não existe. Cadastre um livro primeiro.")


# --- Exclusão ---
def excluir_livro(titulo):
    try:
        encontrado = False
        linhas_mantidas = []

        with open(ARQUIVO, "r", encoding="utf-8") as f:
            for linha in f:
                nome, autor = linha.strip().split(";")
                if nome.lower() != titulo.lower():
                    linhas_mantidas.append(linha)
                else:
                    encontrado = True

        with open(ARQUIVO, "w", encoding="utf-8") as f:
            f.writelines(linhas_mantidas)

        if encontrado:
            print(f"Livro '{titulo}' removido com sucesso!")
        else:
            print("Livro não encontrado para exclusão.")

    except FileNotFoundError:
        print("Arquivo ainda não existe. Cadastre um livro primeiro.")

open(ARQUIVO, "w", encoding="utf-8").close()
print("Arquivo limpo! Pronto para cadastrar.")

cadastrar_livro("Harry Potter", "J.K. Rowling")
cadastrar_livro("Dom Casmurro", "Machado de Assis")
cadastrar_livro("Orgulho e Preconceito", "Jane Austen")
cadastrar_livro("1984", "George Orwell")

!cat livros.txt

buscar_livro("dom casmurro")

excluir_livro("dom casmurro")

!cat livros.txt